// SPDX-FileCopyrightText: Alexander zur Bonsen <alexander.zur.bonsen@tngtech.com>
//
// SPDX-License-Identifier: Apache-2.0
export const STORAGE_KEYS = {
  DOMAIN_STATS: 'domainStats',
  MONITORING_ACTIVE: 'monitoringActive',
  GREEN_HOSTING_FACTOR: 'greenHostingFactor',
  GRID_INTENSITIES: 'gridIntensities',
};

export const LOGGER_PREFIX = 'WEBEXT-CO2';
export const SET_CONFIG_DEBOUNCE_INTERVAL = 500; // ms
export const RE_FETCH_INTERVAL = 5000; // ms

export interface CountryCode {
  alpha3: string;
  country: string;
}

// according to https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
export const COUNTRY_CODE_OPTIONS: readonly CountryCode[] = [
  { alpha3: 'ABW', country: 'Aruba' },
  { alpha3: 'AFG', country: 'Afghanistan' },
  { alpha3: 'AGO', country: 'Angola' },
  { alpha3: 'AIA', country: 'Anguilla' },
  { alpha3: 'ALA', country: 'Åland Islands' },
  { alpha3: 'ALB', country: 'Albania' },
  { alpha3: 'AND', country: 'Andorra' },
  { alpha3: 'ARE', country: 'United Arab Emirates' },
  { alpha3: 'ARG', country: 'Argentina' },
  { alpha3: 'ARM', country: 'Armenia' },
  { alpha3: 'ASM', country: 'American Samoa' },
  { alpha3: 'ATA', country: 'Antarctica' },
  { alpha3: 'ATF', country: 'French Southern Territories' },
  { alpha3: 'ATG', country: 'Antigua and Barbuda' },
  { alpha3: 'AUS', country: 'Australia' },
  { alpha3: 'AUT', country: 'Austria' },
  { alpha3: 'AZE', country: 'Azerbaijan' },
  { alpha3: 'BDI', country: 'Burundi' },
  { alpha3: 'BEL', country: 'Belgium' },
  { alpha3: 'BEN', country: 'Benin' },
  { alpha3: 'BES', country: 'Bonaire, Sint Eustatius and Saba' },
  { alpha3: 'BFA', country: 'Burkina Faso' },
  { alpha3: 'BGD', country: 'Bangladesh' },
  { alpha3: 'BGR', country: 'Bulgaria' },
  { alpha3: 'BHR', country: 'Bahrain' },
  { alpha3: 'BHS', country: 'Bahamas' },
  { alpha3: 'BIH', country: 'Bosnia and Herzegovina' },
  { alpha3: 'BLM', country: 'Saint Barthélemy' },
  { alpha3: 'BLR', country: 'Belarus' },
  { alpha3: 'BLZ', country: 'Belize' },
  { alpha3: 'BMU', country: 'Bermuda' },
  { alpha3: 'BOL', country: 'Bolivia, Plurinational State of' },
  { alpha3: 'BRA', country: 'Brazil' },
  { alpha3: 'BRB', country: 'Barbados' },
  { alpha3: 'BRN', country: 'Brunei Darussalam' },
  { alpha3: 'BTN', country: 'Bhutan' },
  { alpha3: 'BVT', country: 'Bouvet Island' },
  { alpha3: 'BWA', country: 'Botswana' },
  { alpha3: 'CAF', country: 'Central African Republic' },
  { alpha3: 'CAN', country: 'Canada' },
  { alpha3: 'CCK', country: 'Cocos (Keeling) Islands' },
  { alpha3: 'CHE', country: 'Switzerland' },
  { alpha3: 'CHL', country: 'Chile' },
  { alpha3: 'CHN', country: 'China' },
  { alpha3: 'CIV', country: "Côte d'Ivoire" },
  { alpha3: 'CMR', country: 'Cameroon' },
  { alpha3: 'COD', country: 'Congo, Democratic Republic of the' },
  { alpha3: 'COG', country: 'Congo' },
  { alpha3: 'COK', country: 'Cook Islands' },
  { alpha3: 'COL', country: 'Colombia' },
  { alpha3: 'COM', country: 'Comoros' },
  { alpha3: 'CPV', country: 'Cabo Verde' },
  { alpha3: 'CRI', country: 'Costa Rica' },
  { alpha3: 'CUB', country: 'Cuba' },
  { alpha3: 'CUW', country: 'Curaçao' },
  { alpha3: 'CXR', country: 'Christmas Island' },
  { alpha3: 'CYM', country: 'Cayman Islands' },
  { alpha3: 'CYP', country: 'Cyprus' },
  { alpha3: 'CZE', country: 'Czechia' },
  { alpha3: 'DEU', country: 'Germany' },
  { alpha3: 'DJI', country: 'Djibouti' },
  { alpha3: 'DMA', country: 'Dominica' },
  { alpha3: 'DNK', country: 'Denmark' },
  { alpha3: 'DOM', country: 'Dominican Republic' },
  { alpha3: 'DZA', country: 'Algeria' },
  { alpha3: 'ECU', country: 'Ecuador' },
  { alpha3: 'EGY', country: 'Egypt' },
  { alpha3: 'ERI', country: 'Eritrea' },
  { alpha3: 'ESH', country: 'Western Sahara' },
  { alpha3: 'ESP', country: 'Spain' },
  { alpha3: 'EST', country: 'Estonia' },
  { alpha3: 'ETH', country: 'Ethiopia' },
  { alpha3: 'FIN', country: 'Finland' },
  { alpha3: 'FJI', country: 'Fiji' },
  { alpha3: 'FLK', country: 'Falkland Islands (Malvinas)' },
  { alpha3: 'FRA', country: 'France' },
  { alpha3: 'FRO', country: 'Faroe Islands' },
  { alpha3: 'FSM', country: 'Micronesia, Federated States of' },
  { alpha3: 'GAB', country: 'Gabon' },
  {
    alpha3: 'GBR',
    country: 'United Kingdom of Great Britain and Northern Ireland',
  },
  { alpha3: 'GEO', country: 'Georgia' },
  { alpha3: 'GGY', country: 'Guernsey' },
  { alpha3: 'GHA', country: 'Ghana' },
  { alpha3: 'GIB', country: 'Gibraltar' },
  { alpha3: 'GIN', country: 'Guinea' },
  { alpha3: 'GLP', country: 'Guadeloupe' },
  { alpha3: 'GMB', country: 'Gambia' },
  { alpha3: 'GNB', country: 'Guinea-Bissau' },
  { alpha3: 'GNQ', country: 'Equatorial Guinea' },
  { alpha3: 'GRC', country: 'Greece' },
  { alpha3: 'GRD', country: 'Grenada' },
  { alpha3: 'GRL', country: 'Greenland' },
  { alpha3: 'GTM', country: 'Guatemala' },
  { alpha3: 'GUF', country: 'French Guiana' },
  { alpha3: 'GUM', country: 'Guam' },
  { alpha3: 'GUY', country: 'Guyana' },
  { alpha3: 'HKG', country: 'Hong Kong' },
  { alpha3: 'HMD', country: 'Heard Island and McDonald Islands' },
  { alpha3: 'HND', country: 'Honduras' },
  { alpha3: 'HRV', country: 'Croatia' },
  { alpha3: 'HTI', country: 'Haiti' },
  { alpha3: 'HUN', country: 'Hungary' },
  { alpha3: 'IDN', country: 'Indonesia' },
  { alpha3: 'IMN', country: 'Isle of Man' },
  { alpha3: 'IND', country: 'India' },
  { alpha3: 'IOT', country: 'British Indian Ocean Territory' },
  { alpha3: 'IRL', country: 'Ireland' },
  { alpha3: 'IRN', country: 'Iran, Islamic Republic of' },
  { alpha3: 'IRQ', country: 'Iraq' },
  { alpha3: 'ISL', country: 'Iceland' },
  { alpha3: 'ISR', country: 'Israel' },
  { alpha3: 'ITA', country: 'Italy' },
  { alpha3: 'JAM', country: 'Jamaica' },
  { alpha3: 'JEY', country: 'Jersey' },
  { alpha3: 'JOR', country: 'Jordan' },
  { alpha3: 'JPN', country: 'Japan' },
  { alpha3: 'KAZ', country: 'Kazakhstan' },
  { alpha3: 'KEN', country: 'Kenya' },
  { alpha3: 'KGZ', country: 'Kyrgyzstan' },
  { alpha3: 'KHM', country: 'Cambodia' },
  { alpha3: 'KIR', country: 'Kiribati' },
  { alpha3: 'KNA', country: 'Saint Kitts and Nevis' },
  { alpha3: 'KOR', country: 'Korea, Republic of' },
  { alpha3: 'KWT', country: 'Kuwait' },
  { alpha3: 'LAO', country: "Lao People's Democratic Republic" },
  { alpha3: 'LBN', country: 'Lebanon' },
  { alpha3: 'LBR', country: 'Liberia' },
  { alpha3: 'LBY', country: 'Libya' },
  { alpha3: 'LCA', country: 'Saint Lucia' },
  { alpha3: 'LIE', country: 'Liechtenstein' },
  { alpha3: 'LKA', country: 'Sri Lanka' },
  { alpha3: 'LSO', country: 'Lesotho' },
  { alpha3: 'LTU', country: 'Lithuania' },
  { alpha3: 'LUX', country: 'Luxembourg' },
  { alpha3: 'LVA', country: 'Latvia' },
  { alpha3: 'MAC', country: 'Macao' },
  { alpha3: 'MAF', country: 'Saint Martin (French part)' },
  { alpha3: 'MAR', country: 'Morocco' },
  { alpha3: 'MCO', country: 'Monaco' },
  { alpha3: 'MDA', country: 'Moldova, Republic of' },
  { alpha3: 'MDG', country: 'Madagascar' },
  { alpha3: 'MDV', country: 'Maldives' },
  { alpha3: 'MEX', country: 'Mexico' },
  { alpha3: 'MHL', country: 'Marshall Islands' },
  { alpha3: 'MKD', country: 'North Macedonia' },
  { alpha3: 'MLI', country: 'Mali' },
  { alpha3: 'MLT', country: 'Malta' },
  { alpha3: 'MMR', country: 'Myanmar' },
  { alpha3: 'MNE', country: 'Montenegro' },
  { alpha3: 'MNG', country: 'Mongolia' },
  { alpha3: 'MNP', country: 'Northern Mariana Islands' },
  { alpha3: 'MOZ', country: 'Mozambique' },
  { alpha3: 'MRT', country: 'Mauritania' },
  { alpha3: 'MSR', country: 'Montserrat' },
  { alpha3: 'MTQ', country: 'Martinique' },
  { alpha3: 'MUS', country: 'Mauritius' },
  { alpha3: 'MWI', country: 'Malawi' },
  { alpha3: 'MYS', country: 'Malaysia' },
  { alpha3: 'MYT', country: 'Mayotte' },
  { alpha3: 'NAM', country: 'Namibia' },
  { alpha3: 'NCL', country: 'New Caledonia' },
  { alpha3: 'NER', country: 'Niger' },
  { alpha3: 'NFK', country: 'Norfolk Island' },
  { alpha3: 'NGA', country: 'Nigeria' },
  { alpha3: 'NIC', country: 'Nicaragua' },
  { alpha3: 'NIU', country: 'Niue' },
  { alpha3: 'NLD', country: 'Netherlands, Kingdom of the' },
  { alpha3: 'NOR', country: 'Norway' },
  { alpha3: 'NPL', country: 'Nepal' },
  { alpha3: 'NRU', country: 'Nauru' },
  { alpha3: 'NZL', country: 'New Zealand' },
  { alpha3: 'OMN', country: 'Oman' },
  { alpha3: 'PAK', country: 'Pakistan' },
  { alpha3: 'PAN', country: 'Panama' },
  { alpha3: 'PCN', country: 'Pitcairn' },
  { alpha3: 'PER', country: 'Peru' },
  { alpha3: 'PHL', country: 'Philippines' },
  { alpha3: 'PLW', country: 'Palau' },
  { alpha3: 'PNG', country: 'Papua New Guinea' },
  { alpha3: 'POL', country: 'Poland' },
  { alpha3: 'PRI', country: 'Puerto Rico' },
  { alpha3: 'PRK', country: "Korea, Democratic People's Republic of" },
  { alpha3: 'PRT', country: 'Portugal' },
  { alpha3: 'PRY', country: 'Paraguay' },
  { alpha3: 'PSE', country: 'Palestine, State of' },
  { alpha3: 'PYF', country: 'French Polynesia' },
  { alpha3: 'QAT', country: 'Qatar' },
  { alpha3: 'REU', country: 'Réunion' },
  { alpha3: 'ROU', country: 'Romania' },
  { alpha3: 'RUS', country: 'Russian Federation' },
  { alpha3: 'RWA', country: 'Rwanda' },
  { alpha3: 'SAU', country: 'Saudi Arabia' },
  { alpha3: 'SDN', country: 'Sudan' },
  { alpha3: 'SEN', country: 'Senegal' },
  { alpha3: 'SGP', country: 'Singapore' },
  { alpha3: 'SGS', country: 'South Georgia and the South Sandwich Islands' },
  { alpha3: 'SHN', country: 'Saint Helena, Ascension and Tristan da Cunha' },
  { alpha3: 'SJM', country: 'Svalbard and Jan Mayen' },
  { alpha3: 'SLB', country: 'Solomon Islands' },
  { alpha3: 'SLE', country: 'Sierra Leone' },
  { alpha3: 'SLV', country: 'El Salvador' },
  { alpha3: 'SMR', country: 'San Marino' },
  { alpha3: 'SOM', country: 'Somalia' },
  { alpha3: 'SPM', country: 'Saint Pierre and Miquelon' },
  { alpha3: 'SRB', country: 'Serbia' },
  { alpha3: 'SSD', country: 'South Sudan' },
  { alpha3: 'STP', country: 'Sao Tome and Principe' },
  { alpha3: 'SUR', country: 'Suriname' },
  { alpha3: 'SVK', country: 'Slovakia' },
  { alpha3: 'SVN', country: 'Slovenia' },
  { alpha3: 'SWE', country: 'Sweden' },
  { alpha3: 'SWZ', country: 'Eswatini' },
  { alpha3: 'SXM', country: 'Sint Maarten (Dutch part)' },
  { alpha3: 'SYC', country: 'Seychelles' },
  { alpha3: 'SYR', country: 'Syrian Arab Republic' },
  { alpha3: 'TCA', country: 'Turks and Caicos Islands' },
  { alpha3: 'TCD', country: 'Chad' },
  { alpha3: 'TGO', country: 'Togo' },
  { alpha3: 'THA', country: 'Thailand' },
  { alpha3: 'TJK', country: 'Tajikistan' },
  { alpha3: 'TKL', country: 'Tokelau' },
  { alpha3: 'TKM', country: 'Turkmenistan' },
  { alpha3: 'TLS', country: 'Timor-Leste' },
  { alpha3: 'TON', country: 'Tonga' },
  { alpha3: 'TTO', country: 'Trinidad and Tobago' },
  { alpha3: 'TUN', country: 'Tunisia' },
  { alpha3: 'TUR', country: 'Türkiye' },
  { alpha3: 'TUV', country: 'Tuvalu' },
  { alpha3: 'TWN', country: 'Taiwan, Province of China' },
  { alpha3: 'TZA', country: 'Tanzania, United Republic of' },
  { alpha3: 'UGA', country: 'Uganda' },
  { alpha3: 'UKR', country: 'Ukraine' },
  { alpha3: 'UMI', country: 'United States Minor Outlying Islands' },
  { alpha3: 'URY', country: 'Uruguay' },
  { alpha3: 'USA', country: 'United States of America' },
  { alpha3: 'UZB', country: 'Uzbekistan' },
  { alpha3: 'VAT', country: 'Holy See' },
  { alpha3: 'VCT', country: 'Saint Vincent and the Grenadines' },
  { alpha3: 'VEN', country: 'Venezuela, Bolivarian Republic of' },
  { alpha3: 'VGB', country: 'Virgin Islands (British)' },
  { alpha3: 'VIR', country: 'Virgin Islands (U.S.)' },
  { alpha3: 'VNM', country: 'Viet Nam' },
  { alpha3: 'VUT', country: 'Vanuatu' },
  { alpha3: 'WLF', country: 'Wallis and Futuna' },
  { alpha3: 'WSM', country: 'Samoa' },
  { alpha3: 'YEM', country: 'Yemen' },
  { alpha3: 'ZAF', country: 'South Africa' },
  { alpha3: 'ZMB', country: 'Zambia' },
  { alpha3: 'ZWE', country: 'Zimbabwe' },
];
